<?php

namespace app\index\controller;

use app\admin\model\content\App;
use app\admin\model\content\Article;
use app\common\controller\Frontend;
use app\common\model\Category;
use think\Db;

class Index extends Frontend
{

    protected $noNeedLogin = '*';
    protected $noNeedRight = '*';
    protected $layout = '';
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $appcat=Db::name('category')->where('type','app')->order('weigh asc')
            ->select();
        $this->assign('appcat',$appcat);
    }

    public function index()
    {
        $banner=Db::name('banner')->where('category_id','14')->order('weigh desc')
            ->select();
        $app=App::order('weigh desc')->limit(6)->select();
        $this->view->assign('banner',$banner);
        $this->view->assign('app',$app);

        return $this->view->fetch();
    }

    public function contact()
    {

        return $this->view->fetch();

    }
    public function cdn(){
        return $this->view->fetch();

    }

    public function news()
    {
        $article=Article::where('category_id','16')->order('createtime desc')
            ->paginate(10,true);

        return $this->view->fetch('',compact('article'));
    }

    public function newsdetail()
    {
        $id=input('id','1');
        $article=Article::where('id',$id)->find();
        return $this->view->fetch('',compact('article'));

    }

    public function yuanma()
    {
        $id=input('cat',1);
        $app=App::where('category_id',$id)->order('createtime desc')->paginate(8,true,[
            'query' => $this->request->param(),//不丢失已存在的url参数
        ]);
        $cat=Category::find($id);
        return $this->view->fetch('',compact('app','cat'));

    }
    public function yuanmadetail()
    {
        $id=input('id','1');
        $article=App::where('id',$id)->find();
        return $this->view->fetch('',compact('article'));

    }

}
